### ISSUE TITLE
running flappie on ubuntu 18.04

### ISSUE THREAD

**Issue by harisankarsadasivan** [nanoporetech/flappie#34]
im following the instructions for 16.04 for 18.04 as well,

    Running
        libcunit1
        libhdf5
        libopenblas-base
    Building
        cmake
        libcunit1-dev
        libhdf5-dev
        libopenblas-dev
But i cant seem to figure out how to install libhdf5.
tried this as well,
sudo apt-get install libhdf5-serial-dev

**Comment by harisankarsadasivan** [comment]
I'm getting this error while checking trace viewer, hence was checking if I have all dependencies...
Traceback (most recent call last):
  File "misc/trace_flipflop.py", line 185, in <module>
    'BaseCalled_template', 'Trace')][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/hariss/basecaller/flappie/venv/lib/python3.6/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Trace' doesn't exist)"

**Comment by harisankarsadasivan** [comment]
tried this as well,
sudo apt-get install libhdf5-serial-dev

**Comment by tmassingham-ont** [comment]
Hello.  This isn’t an issue with HDF5, the fast5 file you are analysing does not appear to contain trace information.  Guppy does not output the trace information by default, since it significantly increases the size of the fast5 files.  For further help, please consult the Guppy documentation and help forums.
