### ISSUE TITLE
running flappie on ubuntu 16.04

### ISSUE THREAD

**Issue by jacka87164** [nanoporetech/flappie#38]
I encountered this error while running flappie:

Traceback (most recent call last):
  File "misc/trace_flipflop.py", line 187, in <module>
    'BaseCalled_template', 'Trace')][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/root/anaconda2/envs/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Trace' doesn't exist)"

**Comment by tmassingham-ont** [comment]
Hello.  The problem appears to be that the file you are analysing does not contain trace output ('Trace' group). How did you produce the file you are analysing?  Both Guppy and Flappie require trace output to be explicitly turned on, since it can slow down base calling and increases the size of files produced.
